---
distro: bionic
language: generic
install: true

jobs:
  include:
    - name: Linux AMD64 OpenJDK8
      env: JDK_VERSION=8
    - name: Linux AMD64 OpenJDK11
      env: JDK_VERSION=11
    - name: Linux ARM64 OpenJDK11
      arch: arm64
      env: JDK_VERSION=11

before_install:
  - sudo apt update -y
  - sudo apt install openjdk-${JDK_VERSION}-jdk maven

script: ./mvnw test -Ptravis

notifications:
  email:
    - michael@mosmann.de
    - m.joehren@gmail.com
    - schaum@kaffeekrone.de

cache:
  directories:
    - $HOME/.m2/repository
